export enum TagsEnum {
    BUG = 'BUG',
    IMPLEMENTATION = 'IMPLEMENTATION',
    CLOSED = 'CLOSED',
    REOPEN = 'REOPEN',
    ERROR = 'ERROR',
    RESOLVED = 'RESOLVED',
    QUESTION = 'QUESTION',
    HOT = 'HOT',
    DEPRECATED = 'DEPRECATED'
}